//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSportProject.Core.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvatarImage
    {
        public int AvatarId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Path { get; set; }
    }
}
