//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSportProject.Core.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string Postcontent { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string Updateby { get; set; }
    }
}
