//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSportProject.Core.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportProfile
    {
        public int ProfileID { get; set; }
        public int PosplayId { get; set; }
        public int SportId { get; set; }
        public int UserId { get; set; }
        public int Experience { get; set; }
        public string Description { get; set; }
        public string DateCreated { get; set; }
    }
}
