//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSportProject.Core.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSport
    {
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Description { get; set; }
        public string Image_url { get; set; }
        public Nullable<int> SportId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<short> GenderTeam { get; set; }
        public Nullable<int> FromAge { get; set; }
        public Nullable<int> ToAge { get; set; }
    }
}
