//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSportProject.Models.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadium
    {
        public int StadiumId { get; set; }
        public string StadiumName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ImageId { get; set; }
        public int HostId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
    }
}
